# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/OIE/Desktop/arty_holme_gps/arty_holme/arty_holme.srcs/sources_1/ip/blk_cpu_stacks_1/blk_cpu_stacks.xci
# IP: The module: 'blk_cpu_stacks' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/OIE/Desktop/arty_holme_gps/arty_holme/arty_holme.gen/sources_1/ip/blk_cpu_stacks_1/blk_cpu_stacks_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_cpu_stacks'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/OIE/Desktop/arty_holme_gps/arty_holme/arty_holme.srcs/sources_1/ip/blk_cpu_stacks_1/blk_cpu_stacks.xci
# IP: The module: 'blk_cpu_stacks' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/OIE/Desktop/arty_holme_gps/arty_holme/arty_holme.gen/sources_1/ip/blk_cpu_stacks_1/blk_cpu_stacks_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_cpu_stacks'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
